#!/usr/bin/env bash
# shellcheck disable=SC2086

Sub_domain () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | sed -r "s/$1./$2/g" | sed -r "s/ /\t/g" | sed -r "s/\t/ /g" | awk '{ print "The subdomain " $1 " is a " $4 " record and points to "  $5 }'
}

if [ "$#" -eq 2 ]
then
    Sub_domain "$2.$1" "$2"

else
    Sub_domain "www.$1" "www"
    Sub_domain "lb-01.$1" "lb-01"
    Sub_domain "web-01.$1" "web-01"
    Sub_domain "web-02.$1" "web-02"
fi
