#!/usr/bin/env bash
# Install nginx web server.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
