#!/usr/bin/env bash
# Instaall the nginx web server and redirect.
sudo apt-get update
sudo apt-get -y install nginx
sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://github.com/saidskander/;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
