#!/usr/bin/env bash
# Instaall the nginx web server and redirect.
apt-get update
apt-get -y install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://github.com/saidskander/;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
