#!/usr/bin/env bash
# Installs Nginx server and redirect.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /etc/nginx/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/saidskander permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
service nginx start
