#!/usr/bin/env bash
# run nginx as nginx user to popin the permission nginx whn hackers try to hack server
sudo chmod 404 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx start
