#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
sudo chmod 404 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx start
